# Generated by Django 3.1.3 on 2020-12-02 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supershop', '0003_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New order', 'New order'), ('Not delivered', 'Not delivered'), ('In process', 'In process'), ('Delivered', 'Delivered')], default='New order', max_length=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supershop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
