# Generated by Django 3.1.3 on 2020-12-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop', '0004_auto_20201202_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not delivered', 'Not delivered'), ('In process', 'In process'), ('Delivered', 'Delivered')], default='New order', max_length=20),
        ),
    ]
