# Generated by Django 3.1.3 on 2020-12-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supershop', '0006_order_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
