# Generated by Django 3.1.3 on 2020-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
