# Generated by Django 3.1.3 on 2020-12-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201209_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='anonymous.png', upload_to=''),
        ),
    ]
