# Generated by Django 3.1.3 on 2020-12-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201209_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank='True', default='anonym.png', upload_to=''),
        ),
    ]
